name: RC 11 Transaction Check

on:
  workflow_dispatch:  # manual trigger

jobs:
  run-check:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          persist-credentials: false  # Important: use PAT for push
          fetch-depth: 0

      # 2. Set up Python
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      # 3. Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4

      # 4. Run the RC transaction script
      - name: Run RC transaction script
        run: python fricemiss.py

      # 5. Commit and push results using GH_PAT
      - name: Commit and push results
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        run: |
          # Configure Git
          git config --global user.name "pothabattulavinod"
          git config --global user.email "vinodyadavpothabattula666@gmail.com"

          # Ensure JSON file exists and is valid
          if [ ! -s 11trns_current.json ]; then
            echo '{"transactions":[]}' > 11trns_current.json
          fi

          # Stage changes
          git add 11trns_current.json

          # Commit only if there are changes
          if ! git diff-index --quiet HEAD; then
            git commit -m "Update RC transaction results [skip ci]"
          else
            echo "No changes to commit"
          fi

          # Update remote URL to use PAT
          git remote remove origin
          git remote add origin https://x-access-token:${GH_PAT}@github.com/pothabattulavinod/rcklv.git

          # Push current branch to main
          git push origin HEAD:main
